Aut 20 second half of tap actions
Beep1990/DuckDuckGo pull request #11
Opened 2022-07-13 12:41 UTC by MichalWozniak92

Task/Issue URL: 

### Description

### Steps to test this PR

_Feature 1_
- [ ]
- [ ]

### UI changes
| Before  | After |
| ------ | ----- |
!(Upload before screenshot)|(Upload after screenshot)|

2022-07-13 12:52 UTC, Arkadiuswojtasik approved these changes

2022-07-26 09:08 UTC, DawidLukasik1 approved these changes

2022-08-12 11:31 UTC, Beep1990 requested changes

2022-08-12 11:31 UTC, Beep1990 commented on app/src/androidTest/java/com/duckduckgo/actions/TapActions.kt
> +        .perform(actionOnItemAtPosition<ViewHolder>(position, click()))
Tutaj też jest nie do końca poprawnie, powinno być         .perform(actionOnItemAtPosition<RecyclerView.ViewHolder>(position, click()))

2022-08-12 11:31 UTC, Beep1990 commented on app/src/androidTest/java/com/duckduckgo/actions/TapActions.kt
> +import org.hamcrest.CoreMatchers
To zmienić na 
import org.hamcrest.*
import org.hamcrest.CoreMatchers.allOf

2022-08-12 11:31 UTC, Beep1990 commented on app/src/androidTest/java/com/duckduckgo/actions/TapActions.kt
> +    onView(CoreMatchers.allOf(withId(viewId), ViewMatchers.withText(stringId)))
Po zmianie importów usunąć wszędzie CoreMatchers. Będzie to ładniej w kodzie wyglądało

2022-08-12 11:31 UTC, Beep1990 commented on app/src/androidTest/java/com/duckduckgo/actions/TapActions.kt
> +    onView(CoreMatchers.allOf(withId(viewId), ViewMatchers.withText(stringId)))
CoreMatchers. do wywalenia

2022-08-12 11:31 UTC, Beep1990 commented on app/src/androidTest/java/com/duckduckgo/actions/TapActions.kt
> +    onView(CoreMatchers.allOf(withId(viewId), ViewMatchers.withText(stringId)))
CoreMatchers. do wywalenia

2022-09-20 06:15 UTC, Beep1990 approved these changes

2022-09-20 06:15 UTC, Beep1990 commented on app/src/androidTest/java/com/duckduckgo/actions/TapActions.kt
> +<<<<<<< HEAD
to jest niepotrzebne :D

2022-09-20 06:15 UTC, Beep1990 commented on app/src/androidTest/java/com/duckduckgo/actions/TapActions.kt
> +=======
i to też

2022-09-20 06:15 UTC, Beep1990 commented on app/src/androidTest/java/com/duckduckgo/actions/TapActions.kt
i tu ten pusty space też do zlikwidowania

2022-09-20 06:15 UTC, merged