Add turn off animation rule
Beep1990/DuckDuckGo pull request #5
Opened 2022-05-19 11:25 UTC by MichalWozniak92

2022-05-19 17:04 UTC, Beep1990 approved these changes

2022-05-19 17:05 UTC, Beep1990 commented on app/src/androidTest/java/com/duckduckgo/rules/TurnOffAnimationRule.kt
> +
Niepotrzebna pusta linia

2022-05-19 17:08 UTC, Beep1990 requested changes
Poprawka formatowania z komentarza wyżej i będzie git

2022-05-23 09:12 UTC, lukasikdpp approved these changes

2022-05-24 10:59 UTC, Beep1990 approved these changes

2022-05-25 07:41 UTC, Arkadiuswojtasik approved these changes

2022-05-25 07:42 UTC, merged